databases:
  - name: postgres
    ipAllowList: []
    databaseName: free_hot_tubs
    user: heydanhey

services:
  - type: web
    name: free_hot_tubs
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false